### ISSUE TITLE
Feature Request: Support for Centralized and Dynamic Configuration

### ISSUE THREAD

**Issue by AmitMizrahiDev** [reportportal/agent-dotnet-xunit.v3#3]
Currently, the agent requires a static JSON configuration file per project to connect to ReportPortal.
In our organization, we have multiple test projects (each representing a different microservice), and we’d like all of them to connect to a single shared infrastructure layer (a common ReportPortal configuration).

We want to maintain one centralized configuration that can be used by all test projects, rather than duplicating a static reportportal.config.json in each project.
Additionally, we’d like the agent to support dynamic configuration loading — for example, by providing configuration values programmatically at runtime (via environment variables, configuration providers, or a shared C# library).

**Comment by nvborisenko** [comment]
@AmitMizrahiDev please read https://github.com/reportportal/agent-dotnet-xunit.v3?tab=readme-ov-file#configuration, which additionally refers to https://github.com/reportportal/commons-net/blob/master/docs/Configuration.md (we should fix this link, but idea is the same).

UPD: fixed link.

**Comment by AmitMizrahiDev** [comment]
@nvborisenko I read it, and I still don't understand what I should do. 
Maybe you have a code example?
